# Generated by Django 2.2 on 2019-04-13 02:42

from django.db import migrations, models
import platformservices.models


class Migration(migrations.Migration):

    dependencies = [
        ('platformservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', platformservices.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
