# Generated by Django 2.2 on 2019-04-13 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformservices', '0002_auto_20190413_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='name',
            new_name='res_name',
        ),
    ]
