# Generated by Django 2.2 on 2019-04-13 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformservices', '0003_auto_20190413_0251'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
