# Generated by Django 2.2 on 2019-04-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformservices', '0004_auto_20190413_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='unique_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
